# Generated by Django 2.2.19 on 2022-09-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emissor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('codEmissor', models.CharField(max_length=100, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Emissor',
                'verbose_name_plural': 'Emissores',
            },
        ),
    ]
