# Generated by Django 4.1.1 on 2022-11-29 00:47

import aplic.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coletor_Pf",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("telefone", models.CharField(max_length=11, verbose_name="Telefone")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "foto",
                    stdimage.models.StdImageField(
                        blank=True,
                        force_min_size=False,
                        null=True,
                        upload_to=aplic.models.get_file_path,
                        variations={
                            "thumb": {"crop": True, "height": 480, "width": 480}
                        },
                        verbose_name="Foto",
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Facebook"
                    ),
                ),
                (
                    "linkedin",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="LinkedIn"
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Twitter"
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Instagram"
                    ),
                ),
            ],
            options={
                "verbose_name": "Coletor",
                "verbose_name_plural": "Coletores",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Coletor_Pj",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("telefone", models.CharField(max_length=11, verbose_name="Telefone")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "foto",
                    stdimage.models.StdImageField(
                        blank=True,
                        force_min_size=False,
                        null=True,
                        upload_to=aplic.models.get_file_path,
                        variations={
                            "thumb": {"crop": True, "height": 480, "width": 480}
                        },
                        verbose_name="Foto",
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Facebook"
                    ),
                ),
                (
                    "linkedin",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="LinkedIn"
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Twitter"
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Instagram"
                    ),
                ),
            ],
            options={
                "verbose_name": "Coletor",
                "verbose_name_plural": "Coletores",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Emissor_Pf",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("telefone", models.CharField(max_length=11, verbose_name="Telefone")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "foto",
                    stdimage.models.StdImageField(
                        blank=True,
                        force_min_size=False,
                        null=True,
                        upload_to=aplic.models.get_file_path,
                        variations={
                            "thumb": {"crop": True, "height": 480, "width": 480}
                        },
                        verbose_name="Foto",
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Facebook"
                    ),
                ),
                (
                    "linkedin",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="LinkedIn"
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Twitter"
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Instagram"
                    ),
                ),
                (
                    "imagem",
                    stdimage.models.StdImageField(
                        blank=True,
                        force_min_size=False,
                        null=True,
                        upload_to=aplic.models.get_file_path,
                        variations={
                            "thumb": {"crop": True, "height": 260, "width": 420}
                        },
                        verbose_name="Imagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emissor",
                "verbose_name_plural": "Emissores",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Emissor_Pj",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("telefone", models.CharField(max_length=11, verbose_name="Telefone")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "foto",
                    stdimage.models.StdImageField(
                        blank=True,
                        force_min_size=False,
                        null=True,
                        upload_to=aplic.models.get_file_path,
                        variations={
                            "thumb": {"crop": True, "height": 480, "width": 480}
                        },
                        verbose_name="Foto",
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Facebook"
                    ),
                ),
                (
                    "linkedin",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="LinkedIn"
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Twitter"
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Instagram"
                    ),
                ),
                (
                    "imagem",
                    stdimage.models.StdImageField(
                        blank=True,
                        force_min_size=False,
                        null=True,
                        upload_to=aplic.models.get_file_path,
                        variations={
                            "thumb": {"crop": True, "height": 260, "width": 420}
                        },
                        verbose_name="Imagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emissor",
                "verbose_name_plural": "Emissores",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logradouro",
                    models.CharField(max_length=200, verbose_name="Logradouro"),
                ),
                ("numero", models.CharField(max_length=10, verbose_name="Número")),
                ("cidade", models.CharField(max_length=50, verbose_name="Cidade")),
                ("bairro", models.CharField(max_length=100, verbose_name="Bairro")),
                (
                    "complemento",
                    models.CharField(max_length=200, verbose_name="Complemento"),
                ),
                ("cep", models.CharField(max_length=8, verbose_name="CEP")),
            ],
            options={"verbose_name": "Endereço", "verbose_name_plural": "Endereços",},
        ),
        migrations.CreateModel(
            name="PagamentoTaxaColeta",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=200, verbose_name="Status")),
                ("desconto", models.FloatField(verbose_name="Desconto")),
            ],
        ),
        migrations.CreateModel(
            name="SolicitacaoColeta",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.FloatField(max_length=200, verbose_name="Valor")),
                (
                    "dataSolicitacao",
                    models.DateField(max_length=10, verbose_name="Data"),
                ),
                ("qtdItens", models.IntegerField(verbose_name="Quantidade de Itens")),
                (
                    "tipoProduto",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Celular", "Celular"),
                            ("Computador", "Computador"),
                            ("Televisao", "Televisao"),
                            ("Carregador", "Carregador"),
                        ],
                        max_length=100,
                        verbose_name="Tipo de Produto",
                    ),
                ),
                (
                    "coletorPf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="aplic.coletor_pf",
                    ),
                ),
            ],
        ),
    ]
