# Generated by Django 2.2.19 on 2022-09-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coletor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('codColetor', models.CharField(max_length=100, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Coletor',
                'verbose_name_plural': 'Coletores',
            },
        ),
    ]
