# Generated by Django 4.1.1 on 2022-11-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coletor_pf",
            name="facebook",
            field=models.CharField(blank=True, max_length=200, verbose_name="Facebook"),
        ),
        migrations.AddField(
            model_name="coletor_pf",
            name="instagram",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Instagram"
            ),
        ),
        migrations.AddField(
            model_name="coletor_pf",
            name="linkedin",
            field=models.CharField(blank=True, max_length=200, verbose_name="LinkedIn"),
        ),
        migrations.AddField(
            model_name="coletor_pf",
            name="twitter",
            field=models.CharField(blank=True, max_length=200, verbose_name="Twitter"),
        ),
        migrations.AddField(
            model_name="coletor_pj",
            name="facebook",
            field=models.CharField(blank=True, max_length=200, verbose_name="Facebook"),
        ),
        migrations.AddField(
            model_name="coletor_pj",
            name="instagram",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Instagram"
            ),
        ),
        migrations.AddField(
            model_name="coletor_pj",
            name="linkedin",
            field=models.CharField(blank=True, max_length=200, verbose_name="LinkedIn"),
        ),
        migrations.AddField(
            model_name="coletor_pj",
            name="twitter",
            field=models.CharField(blank=True, max_length=200, verbose_name="Twitter"),
        ),
        migrations.AddField(
            model_name="emissor_pf",
            name="facebook",
            field=models.CharField(blank=True, max_length=200, verbose_name="Facebook"),
        ),
        migrations.AddField(
            model_name="emissor_pf",
            name="instagram",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Instagram"
            ),
        ),
        migrations.AddField(
            model_name="emissor_pf",
            name="linkedin",
            field=models.CharField(blank=True, max_length=200, verbose_name="LinkedIn"),
        ),
        migrations.AddField(
            model_name="emissor_pf",
            name="twitter",
            field=models.CharField(blank=True, max_length=200, verbose_name="Twitter"),
        ),
        migrations.AddField(
            model_name="emissor_pj",
            name="facebook",
            field=models.CharField(blank=True, max_length=200, verbose_name="Facebook"),
        ),
        migrations.AddField(
            model_name="emissor_pj",
            name="instagram",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Instagram"
            ),
        ),
        migrations.AddField(
            model_name="emissor_pj",
            name="linkedin",
            field=models.CharField(blank=True, max_length=200, verbose_name="LinkedIn"),
        ),
        migrations.AddField(
            model_name="emissor_pj",
            name="twitter",
            field=models.CharField(blank=True, max_length=200, verbose_name="Twitter"),
        ),
    ]
