# Generated by Django 4.1.1 on 2022-11-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitacaocoleta",
            name="tipoProduto",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Celular", "Celular"),
                    ("Computador", "Computador"),
                    ("Televisao", "Televisao"),
                    ("Carregador", "Carregador"),
                    ("Pilha", "Pilha"),
                    ("Outros", "Outros"),
                ],
                max_length=100,
                verbose_name="Tipo de Produto",
            ),
        ),
    ]
