# Generated by Django 4.1.1 on 2022-11-06 21:51

import aplic.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ("aplic", "0002_coletor_pf_facebook_coletor_pf_instagram_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coletor_pf",
            name="imagem",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                null=True,
                upload_to=aplic.models.get_file_path,
                variations={"thumb": {"crop": True, "height": 260, "width": 420}},
                verbose_name="Imagem",
            ),
        ),
        migrations.AddField(
            model_name="coletor_pj",
            name="imagem",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                null=True,
                upload_to=aplic.models.get_file_path,
                variations={"thumb": {"crop": True, "height": 260, "width": 420}},
                verbose_name="Imagem",
            ),
        ),
        migrations.AddField(
            model_name="emissor_pf",
            name="imagem",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                null=True,
                upload_to=aplic.models.get_file_path,
                variations={"thumb": {"crop": True, "height": 260, "width": 420}},
                verbose_name="Imagem",
            ),
        ),
        migrations.AddField(
            model_name="emissor_pj",
            name="imagem",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                null=True,
                upload_to=aplic.models.get_file_path,
                variations={"thumb": {"crop": True, "height": 260, "width": 420}},
                verbose_name="Imagem",
            ),
        ),
    ]
