# Generated by Django 2.2.19 on 2022-09-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_solicitacaocoleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoTaxaColeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codPagamento', models.CharField(max_length=100, verbose_name='Código')),
                ('status', models.CharField(max_length=200, verbose_name='Status')),
                ('desconto', models.FloatField(max_length=10, verbose_name='Desconto')),
            ],
        ),
        migrations.AlterField(
            model_name='solicitacaocoleta',
            name='valor',
            field=models.FloatField(max_length=200, verbose_name='Valor'),
        ),
    ]
