# Generated by Django 4.1.1 on 2022-11-26 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aplic", "0005_endereco_coletor"),
    ]

    operations = [
        migrations.RemoveField(model_name="endereco", name="coletor",),
    ]
